### ISSUE TITLE
Suggestion for more usefulness + building executables.

### ISSUE THREAD

**Issue by YisusGaming** [shawnjb/ishere#1]
# Suggestion
The readme says that the files you wish to check have to be in the same directory as the script, if not, provide a path to the directory where the files is. I think the script will be more useful if it just received a path to a file to check.
Something like this:
```
ishere ./relative/path/to/file
```
If the file exists, returns the success message. If not, returns the error message.

# Executables
It is possible to embed Lua code into C code. This means that a simple C file that executes the Lua code could be compiled with `gcc` producing an executable.

I'm not completely sure on this, but the produced executable could be almost independent. This means that the executable will only depend on the script source and nothing else, so it could be executed in a machine without the Lua interpreter. As I said, I'm not completely sure on this but I could do the testing necessary.

# PR
I know how this changes could be implemented but I didn't find any `CONTRIBUTING` section or file so I'm unsure if I could implement this and make a PR.

**Comment by YisusGaming** [comment]
I've been testing some code and scenarios. 
/

**Comment by YisusGaming** [comment]
I've been testing some code and scenarios. The script behavior could still be the same, but I'd like to see the executables implemented.

**Comment by YisusGaming** [comment]
Maybe having a `src` folder to separate the Lua and C files from all other repository files could be better?
I'd like to see what you think, @shawnjb.

**Comment by shawnjb** [comment]
The script behavior is great, I did try to rewrite the program in C but it very friendly in terms of dynamic arguments. Your idea of compiling a C program that executes the script seems logical but I am not familiar with the compilation process for such a program so I wouldn't have a say in how that could work.

**Comment by YisusGaming** [comment]
I've been using this C program method for some of my own projects. My idea for this project could work like this:
- In C program, we execute the Lua script using Lua's C API.
- The C program would be the one that has the arguments that the script needs, so we could push them as Globals using the same API.

From that point, the script should execute normally.
About the compilation process, all you'll need is a C compiler, and the Lua Virtual Machine (is a .dll file that comes with Lua's installation), and a Makefile.

**Comment by YisusGaming** [comment]
I forgot to mention: a copy of `include/lua` could be put in the project as well. All the headers files needed to interact with Lua's VM are there.

**Comment by YisusGaming** [comment]
I could start working on a implementation and making a pull request so you could see all the changes this will need.

**Comment by shawnjb** [comment]
> I could start working on an implementation and making a pull request so you could see all the changes this will need.

You can go ahead and make a pull request and I can do some tests to see how it goes. As for the include file, if there's a way to reference the file without including it in the repository of the project, that'd be good to know.

**Comment by shawnjb** [comment]
I'd assume using a Makefile or a batchfile/bash script to retrieve the file(s) from a host would be reasonable to do. I typically keep my projects proprietary source only, as much as I can.

**Comment by YisusGaming** [comment]
It could be defined in the Makefile as some kind of "flag". This way, the user must provide the path to `include/lua` and the path to the Lua's VM (in the case of Lua 5.4, the file will be named `lua54.dll`) to the `make` command.
Something like:
```
make LUA_INCLUDE="/usr/local/include/" LUA_VM="/usr/local/bin/lua54.dll"
```

Note that this would difficult the use of the API since the headers won't really exist in the project/repo.

It could be solved by placing a copy in the project but ignoring it using `.gitignore`, I'm not sure.

**Comment by YisusGaming** [comment]
> It could be solved by placing a copy in the project but ignoring it using `.gitignore`, I'm not sure.

I'm currently on the Makefile step. I'm thinking to use the `.gitignore` approach. Is that ok?

**Comment by shawnjb** [comment]
This issue has been addressed and is now a feature.
